server:
  port: 8080

spring:
  application:
    name: be_template
  config:
    activate:
      on-profile: test
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:~test
      username: sa
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
        show-sql: true